name: 🧪 Coverage Check

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

jobs:
  widget-test:
    name: 🔥 Run Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: subosito/flutter-action@v2.11.0
        with:
          channel: "stable"
      - run: flutter test --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        # env:
        #   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
